const DATA={project:'如如邪修研究所',source_board_url:'https://www.xiaohongshu.com/board/68c701fe000000002400a131?xhsshare=CopyLink&appuid=5ad5ea9311be105ccc77abcb&apptime=1785603137&share_id=a07710a33b8a4de58ccec7e25c42a03a',items:window.XIE_DATA||[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=s=>String(s||'').toLowerCase().replace(/[\s，。！？、,.!?:：;；\-_/]/g,'');
const KEY='ruru_xiexiu_v3_local';
const state={all:[],filtered:[],query:'',category:'全部',view:'all',sort:'order'};
const MEMES=['看起来很邪门，先别急着报警。','收藏不等于会了，点开才算积德。','能不洗碗的配方，拥有天然传播优势。','方法可以野，脑子不能丢。','主打一个：不走寻常路，但走食品安全法。','互联网没有偏方，只有还没翻车的方法。','电子功德 +1，实测反馈 +10086。','这波属于：技能点歪了，但确实有用。'];

const isMobileDevice=()=>/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent)||((navigator.maxTouchPoints||0)>1&&innerWidth<1024);
function noteIdOf(i){const raw=String(i.noteId||i.note_id||i.original_post_url||'');const m=raw.match(/(?:explore|discovery\/item)\/([0-9a-f]{24})/i)||raw.match(/\b([0-9a-f]{24})\b/i);return m?m[1]:''}
function appLinkOf(i){const id=noteIdOf(i);return id?`xhsdiscover://item/${id}?source=deeplink`:''}
function webLinkOf(i){const raw=i.original_post_url||'';const id=noteIdOf(i);if(!raw||!id)return raw;try{const u=new URL(raw);u.pathname=`/discovery/item/${id}`;return u.toString()}catch{return raw}}
function openPost(i){const web=webLinkOf(i)||i.original_post_url;if(!isMobileDevice()||!noteIdOf(i)){window.open(web,'_blank','noopener,noreferrer');return}
  let leftPage=false,timer;
  const done=()=>{leftPage=true;clearTimeout(timer);document.removeEventListener('visibilitychange',watch);window.removeEventListener('pagehide',done)};
  const watch=()=>{if(document.hidden)done()};
  document.addEventListener('visibilitychange',watch);window.addEventListener('pagehide',done,{once:true});
  location.href=appLinkOf(i);
  timer=setTimeout(()=>{document.removeEventListener('visibilitychange',watch);window.removeEventListener('pagehide',done);if(!leftPage)location.href=web},1600);
}
function bindPostOpeners(root=document){root.querySelectorAll('[data-open-post]').forEach(el=>{el.onclick=e=>{e.preventDefault();const i=state.all.find(x=>String(x.id)===String(el.dataset.openPost));if(i)openPost(i)}})}
function buildTicker(){const text=[...MEMES,...MEMES].map(x=>`<span><b>今日精神状态：</b>${esc(x)}</span>`).join('');$('#tickerTrack').innerHTML=text}
function loadLocal(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function saveLocal(){const out={};state.all.forEach(i=>out[i.id]={user_verdict:i.user_verdict||'还没试',user_note:i.user_note||'',original_post_url:i.original_post_url||null});localStorage.setItem(KEY,JSON.stringify(out));updateStats()}
function updateStats(){$('#triedCount').textContent=state.all.filter(i=>i.user_verdict&&i.user_verdict!=='还没试'&&i.user_verdict!=='未试').length}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function riskHot(i){return i.ui_warning==='先别梭哈'}
function friendlyStatus(i){if(i.ui_warning==='先别梭哈')return '先别梭哈';if(i.status==='需看原帖判断'||i.needs_deep_dive)return '先看原帖';return '可围观'}
function renderCategories(){const counts={};state.all.forEach(i=>counts[i.initial_category]=(counts[i.initial_category]||0)+1);const wrap=$('#categoryFilters');wrap.innerHTML=`<button class="filter active" data-category="全部">全门派 ${state.all.length}</button>`+Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<button class="filter" data-category="${esc(k)}">${esc(k)} ${v}</button>`).join('');wrap.querySelectorAll('button').forEach(b=>b.onclick=()=>{wrap.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.category=b.dataset.category;apply()})}
function score(i,q){const n=norm(q);if(!n)return 0;const f=[i.visible_title,i.author,i.initial_category,i.ui_category,(i.initial_tags||[]).join(''),i.method_summary,i.ui_summary,i.risk_screening].map(norm);let s=0;f.forEach((x,idx)=>{if(x.includes(n))s+=idx===0?10:4;for(const ch of n)if(x.includes(ch))s+=.04});return s}
function apply(){let a=state.all.filter(i=>state.category==='全部'||i.initial_category===state.category);if(state.query)a=a.map(i=>[i,score(i,state.query)]).filter(x=>x[1]>.25).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);if(state.view==='watch')a=a.filter(i=>i.original_post_url);if(state.view==='caution')a=a.filter(riskHot);if(state.view==='tried')a=a.filter(i=>i.user_verdict&&i.user_verdict!=='还没试'&&i.user_verdict!=='未试');if(!state.query){const danger={'先别梭哈':0,'看完再动手':1,'邪门但可围观':2};a.sort((x,y)=>state.sort==='category'?x.initial_category.localeCompare(y.initial_category,'zh-CN')||x.id-y.id:state.sort==='risk'?(danger[x.ui_warning]??9)-(danger[y.ui_warning]??9)||x.id-y.id:x.id-y.id)}state.filtered=a;render()}
function card(i){const tags=(i.initial_tags||[]).slice(0,4).map(t=>`<span class="tag">${esc(t)}</span>`).join('');return `<article class="card" data-category="${esc(i.initial_category)}"><div class="card-top"></div><span class="stamp">${i.original_post_url?'原帖健在':'待招魂'}</span><div class="card-inner"><div class="card-meta"><span class="school">${esc(i.ui_emoji)} ${esc(i.ui_category)}</span><span class="entry-id">#${String(i.id).padStart(2,'0')}</span></div><h3>${esc(i.visible_title)}</h3><div class="author">@${esc(i.author)}</div><div class="human-line">${esc(i.ui_summary)}</div><div class="tags">${tags}</div><div class="warning ${riskHot(i)?'hot':''}">${esc(friendlyStatus(i))}</div><div class="card-actions"><button class="summary-btn" data-summary="${i.id}">先看人话</button><a class="watch-btn" href="${esc(webLinkOf(i))}" data-open-post="${i.id}">原帖精准开演 ↗</a></div></div></article>`}
function render(){$('#cardGrid').innerHTML=state.filtered.map(card).join('');$('#resultText').textContent=`显示 ${state.filtered.length} / ${state.all.length} 篇${state.query?' · “'+state.query+'”':''}`;$('#emptyState').classList.toggle('hide',state.filtered.length>0);$('#cardGrid').classList.toggle('hide',state.filtered.length===0);$$('[data-summary]').forEach(b=>b.onclick=()=>openDetail(+b.dataset.summary,'summary'));bindPostOpeners($('#cardGrid'))}
function summaryPane(i){const verdicts=['还没试','封神','能用','就这','翻车'];return `<div class="tab-pane" data-pane="summary"><div class="info-grid"><div><div class="block summary"><h3>一句人话，别让我猜</h3><p>${esc(i.ui_summary)}</p>${i.page_excerpt?`<p class="small">原帖公开文字：${esc(i.page_excerpt)}</p>`:''}</div><div class="block" style="margin-top:12px"><h3>这条属于什么邪法</h3><p>${esc(i.method_summary||i.safe_summary)}</p><div class="detail-tags">${(i.initial_tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div></div><div><div class="block warning-box"><h3>🚨 别一上头就梭哈</h3><p>${esc(i.risk_screening)}</p><p class="small">翻译：可以试，但别把自己当一次性耗材。</p></div><div class="block" style="margin-top:12px"><h3>你的判词</h3><div class="verdicts">${verdicts.map(v=>`<button data-verdict="${v}" class="${i.user_verdict===v||(!i.user_verdict&&v==='还没试')?'active':''}">${v}</button>`).join('')}</div><textarea class="note-area" id="userNote" placeholder="我用了什么、效果咋样、哪里翻车……">${esc(i.user_note||'')}</textarea><button class="save-btn" id="saveNote">存进我的赛博小本本</button></div></div></div></div>`}
function postPane(i){return `<div class="tab-pane hide" data-pane="post"><div class="post-toolbar"><div><strong>原帖精准开演</strong><span>手机先召唤小红书 App 的具体笔记页；召唤失败再自动回退网页版。</span></div><a class="open-external" href="${esc(webLinkOf(i))}" data-open-post="${i.id}">立刻开演 ↗</a></div><div class="launch-stage"><div class="launch-copy"><b>不去首页，<br>直奔案发现场。</b><p>手机浏览器直接点普通网页链接时，小红书偶尔会把具体笔记参数吞掉，只把人送到首页。现在改成官方 App 深链，按笔记 ID 精确开门。</p><div class="platform-note"><strong>会发生什么：</strong>手机优先打开这篇具体笔记；没装 App 或系统拦截时，约 1.6 秒后回退到对应网页版。电脑仍然直接打开网页原帖。</div></div><div class="launch-card"><div class="big-play">▶</div><h3>去作者原帖看完整视频</h3><p class="small">保留作者、评论和原始上下文，不搬运、不偷视频，也不把你扔在小红书首页自生自灭。</p><div class="launch-actions"><a class="direct-watch" href="${esc(webLinkOf(i))}" data-open-post="${i.id}">🎬 手机精准开原帖</a><a class="secondary-link" href="${esc(i.xiaohongshu_search_url||i.original_post_url)}" target="_blank" rel="noopener noreferrer">还不行？按标题搜</a><button class="copy-post-link" type="button" data-copy-post="${esc(i.original_post_url)}">复制原帖链接</button></div></div></div></div>`}
function openDetail(id,tab='summary'){const i=state.all.find(x=>x.id===id);$('#detailContent').innerHTML=`<div class="detail-head"><div class="detail-kicker">ENTRY ${String(i.id).padStart(3,'0')} · ${esc(i.ui_category)} · ${esc(friendlyStatus(i))}</div><h2>${esc(i.visible_title)}</h2><div class="detail-author">@${esc(i.author)}${i.post_date?' · '+esc(i.post_date):''}</div></div><div class="tabs"><button class="tab" data-tab="summary">先看人话总结</button><button class="tab" data-tab="post">原帖视频开演 ↗</button></div>${summaryPane(i)}${postPane(i)}`;$('#detailDialog').showModal();setTab(tab,i);bindPostOpeners($('#detailContent'));$$('.tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab,i));$$('[data-verdict]').forEach(b=>b.onclick=()=>{i.user_verdict=b.dataset.verdict;saveLocal();openDetail(id,'summary');toast('判词已下：'+b.dataset.verdict)});$('#saveNote').onclick=()=>{i.user_note=$('#userNote').value;saveLocal();toast('已记进赛博小本本')};}
function setTab(tab,i){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('[data-pane]').forEach(p=>p.classList.toggle('hide',p.dataset.pane!==tab));if(tab==='post'){const copy=$('[data-copy-post]');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(i.original_post_url);toast('原帖链接已复制，拿去召唤小红书')}catch(e){toast('浏览器不让复制，长按链接也行')}}}}
function randomItem(){const pool=state.filtered.length?state.filtered:state.all;openDetail(pool[Math.floor(Math.random()*pool.length)].id,'summary')}
function init(){const local=loadLocal();state.all=DATA.items.map(i=>({...i,...(local[i.id]||{}),user_verdict:(local[i.id]?.user_verdict)||i.user_verdict||'还没试'}));$('#heroCount').textContent=state.all.length;$('#linkCount').textContent=state.all.filter(i=>i.original_post_url).length;$('#schoolCount').textContent=new Set(state.all.map(i=>i.initial_category)).size;$('#boardLink').href=DATA.source_board_url;buildTicker();renderCategories();updateStats();apply();bind()}
function bind(){$('#searchInput').oninput=e=>{state.query=e.target.value;apply()};$('#sortSelect').onchange=e=>{state.sort=e.target.value;apply()};$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.view=b.dataset.view;apply()});$('#focusSearch').onclick=()=>{$('#searchInput').focus();$('#catalog').scrollIntoView()};$('#browseBtn').onclick=()=>$('#catalog').scrollIntoView();$('#randomBtn').onclick=$('#randomTop').onclick=randomItem;$$('[data-quick]').forEach(b=>b.onclick=()=>{if(b.dataset.quick==='随机')return randomItem();const target=[...$('#categoryFilters').querySelectorAll('button')].find(x=>x.dataset.category===b.dataset.quick);if(target)target.click();$('#catalog').scrollIntoView()});$('#addBtn').onclick=$('#emptyAdd').onclick=()=>$('#addDialog').showModal();$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d)d.close()});$('#addForm').onsubmit=addItem;$('#exportBtn').onclick=exportJson;$('#importBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=importJson;document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}if(e.key==='Escape')$$('dialog[open]').forEach(d=>d.close())})}
function addItem(e){e.preventDefault();const f=new FormData(e.target),id=Math.max(...state.all.map(i=>+i.id||0))+1,title=f.get('title').trim(),author=f.get('author').trim()||'一位神秘道友',url=f.get('url').trim(),category=f.get('category');const map={'美食邪修':['嘴馋门','🍗'],'美妆邪修':['脸面工程','💄'],'生活邪修':['过日子野路子','🪥'],'修图/拍摄邪修':['赛博易容','📸'],'手工/Cos邪修':['手搓万物','🧵'],'穿搭/发型邪修':['外观补丁包','🪞'],'数码邪修':['电子招魂','💾'],'园艺邪修':['赛博神农','🌱']};const [ui_category,ui_emoji]=map[category]||[category,'🌀'];state.all.push({id,visible_title:title,author,initial_category:category,initial_tags:f.get('tags').split(/[,，]/).map(x=>x.trim()).filter(Boolean),method_summary:f.get('note').trim()||'刚捡回来，方法还没审。',ui_summary:'省流：刚捡回来，先放进库里，后面再慢慢盘。',risk_screening:'正文尚未核验，先别闭眼照做。',status:'需看原帖判断',needs_deep_dive:true,ui_warning:'看完再动手',ui_category,ui_emoji,original_post_url:url||null,user_verdict:'还没试',user_note:f.get('note').trim()});saveLocal();renderCategories();apply();$('#addDialog').close();e.target.reset();toast('新邪修已收编')}
function exportJson(){const out={...DATA,items:state.all,exported_at:new Date().toISOString()};const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='如如邪修研究所_我的更新.json';a.click();URL.revokeObjectURL(a.href);toast('已导出，赛博遗产保住了')}
function importJson(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result),items=Array.isArray(d)?d:d.items;if(!Array.isArray(items))throw 0;state.all=items;saveLocal();renderCategories();apply();toast(`导入 ${items.length} 条，数据库吃饱了`)}catch{toast('这JSON长得不像JSON')}};r.readAsText(f);e.target.value=''}
init();
